"""empty message

Revision ID: 75227957ccf3
Revises: d7f0fe3e6d37
Create Date: 2021-05-06 15:12:30.510117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75227957ccf3'
down_revision = 'd7f0fe3e6d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lesson_Type'), 'lesson', ['Type'], unique=False)
    op.create_index(op.f('ix_question_Answer'), 'question', ['Answer'], unique=False)
    op.create_index(op.f('ix_test_Type'), 'test', ['Type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_Type'), table_name='test')
    op.drop_index(op.f('ix_question_Answer'), table_name='question')
    op.drop_index(op.f('ix_lesson_Type'), table_name='lesson')
    # ### end Alembic commands ###
