"""empty message

Revision ID: b1fb6ba5601a
Revises: 75227957ccf3
Create Date: 2021-05-06 15:12:57.795358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fb6ba5601a'
down_revision = '75227957ccf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_Type', table_name='lesson')
    op.drop_index('ix_question_Answer', table_name='question')
    op.drop_index('ix_test_Type', table_name='test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_test_Type', 'test', ['Type'], unique=False)
    op.create_index('ix_question_Answer', 'question', ['Answer'], unique=False)
    op.create_index('ix_lesson_Type', 'lesson', ['Type'], unique=False)
    # ### end Alembic commands ###
